import {useState,useRef} from 'react';
import {Job,Stage,stages,stageName} from './types';
import {Dialog} from './Dialog';
import {Icon} from './Icon';
import {ApiError} from './api';
interface Props {job?:Job;target?:Stage;mode:'record'|'progress';onClose:()=>void;onSave:(data:Record<string,unknown>)=>Promise<void>;onReload:()=>Promise<void>}
export function RecordForm({job,mode,target,onClose,onSave,onReload}:Props) {
 const initialStage=target||job?.stage||'application';
 const [data,setData]=useState<Record<string,string>>(()=>({company:job?.company||'',role:job?.role||'',city:job?.city||'',salary:job?.salary||'',source:job?.source||'',url:job?.url||'',appliedAt:job?.appliedAt||'',notes:job?.notes||'',action:job?.action||'',date:job?.date.slice(0,10)||'',actionTime:job && job.date.length>10?job.date.slice(11,16):'',dateType:job?.dateType||'none',stage:initialStage,status:initialStage==='result'?(job?.stage==='result'?job.resultType:''):job?.stage===initialStage?job.status:initialStage==='application'?'待投递':'待安排',round:job?.round||'',roundNotes:job?.rounds.find(r=>r.stage===initialStage&&r.round===job.round)?.notes||'',roundResult:job?.rounds.find(r=>r.stage===initialStage&&r.round===job.round)?.result||''}));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[errors,setErrors]=useState<Record<string,string>>({});const lock=useRef(false);
 const update=(name:string,value:string)=>setData(d=>{
  if(name==='round') {const saved=job?.rounds.find(r=>r.stage===d.stage&&r.round===value);return {...d,round:value,roundNotes:saved?.notes||'',roundResult:saved?.result||''};}
  return {...d,[name]:value};
 });
 const waiting=mode==='progress'&&['assessment','interview'].includes(data.stage)&&data.status==='待反馈'&&(job?.stage!==data.stage||job?.status!==data.status);
 const field=(label:string,name:string,required=false,type='text')=><label className={`field ${name==='notes'||name==='roundNotes'?'full-width':''} ${errors[name]?'has-error':''}`}><span className="field-label">{label}{required&&<span className="required" aria-hidden="true"> *</span>}</span>{name==='notes'||name==='roundNotes'?<textarea className="form-control" aria-label={label} name={name} value={data[name]} onChange={e=>update(name,e.target.value)} maxLength={10000}/>:<input className="form-control" aria-label={label} aria-required={required} name={name} type={type} value={data[name]} onChange={e=>update(name,e.target.value)} maxLength={name==='url'?2000:500}/>}<span className="field-error">{errors[name]}</span></label>;
 const actionFields=<section className="form-section" hidden={waiting}><h3>下一步行动 <span className="detail-muted">选填</span></h3><div className="field-grid">{field('行动内容','action')}<label className="field"><span className="field-label">时间类型</span><select className="form-control" aria-label="时间类型" value={data.dateType} onChange={e=>{update('dateType',e.target.value);if(e.target.value==='none'){update('date','');update('actionTime','');}}}><option value="none">暂不设置</option><option value="deadline">截止时间</option><option value="appointment">预约时间</option></select></label>{data.dateType!=='none'&&<>{field('行动日期','date',false,'date')}{field('行动时间（选填）','actionTime',false,'time')}</>}</div></section>;
 async function submit(e:React.FormEvent) {e.preventDefault();if(lock.current)return;const nextErrors:Record<string,string>={};if(mode==='record'){if(!data.company.trim())nextErrors.company='请填写公司名称';if(!data.role.trim())nextErrors.role='请填写岗位名称';}if(mode==='progress'&&data.stage==='result'&&!data.status)nextErrors.status='请选择求职结果';if(!waiting&&data.action.trim()&&data.dateType!=='none'&&!data.date)nextErrors.date='请选择行动日期';setErrors(nextErrors);if(Object.keys(nextErrors).length)return;lock.current=true;setBusy(true);setError('');setConflict(false);
 const action=waiting?'':data.action.trim(), date=!waiting&&action&&data.dateType!=='none'&&data.date?data.date+(data.actionTime?`T${data.actionTime}:00+08:00`:''):'';
 const payload=mode==='record'?Object.fromEntries(['company','role','city','salary','source','url','appliedAt','notes'].map(key=>[key,data[key].trim()])):{stage:data.stage,status:data.status,resultType:data.stage==='result'?data.status:'',round:data.round.trim(),roundNotes:data.roundNotes,roundResult:data.roundResult};
 try{await onSave({...payload,action,date,dateType:date?data.dateType:'none'});}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试。');setConflict(e instanceof ApiError&&e.status===409);}finally{lock.current=false;setBusy(false);}}
 return <Dialog label={mode==='progress'?'更新求职进展':job?'编辑求职记录':'添加求职记录'} className="modal-layer react-form-layer" onClose={()=>!busy&&onClose()}><section className="modal"><header className="modal-header"><div><h2>{mode==='progress'?'更新求职进展':job?'编辑求职记录':'添加求职记录'}</h2><p>{mode==='progress'?`${job?.company} · ${job?.role}`:'先记下公司和岗位，其他信息可以慢慢补充。'}</p></div><button className="icon-button" onClick={onClose} disabled={busy} aria-label="关闭表单"><Icon name="close" size={20}/></button></header>
 <form noValidate onSubmit={submit}><fieldset disabled={busy} className="form-fieldset"><div className="modal-body">{error&&<div className="form-error-banner" role="alert">{error}{conflict&&<button type="button" className="button secondary" onClick={()=>void onReload()}>重新读取最新记录</button>}</div>}
 {mode==='record'?<><div className="form-intro"><span className="status-badge tone-blue">{job?stageName(job.stage):'投递'}</span><span>{job?.status||'待投递'}</span></div><div className="field-grid">{field('公司','company',true)}{field('岗位','role',true)}{field('城市','city')}{field('薪资','salary')}{field('招聘渠道','source')}{field('投递日期','appliedAt',false,'date')}{field('岗位链接','url',false,'url')}{field('备注','notes')}</div>{actionFields}</>:<><div className="progress-flow"><span>{job&&stageName(job.stage)}</span><Icon name="arrow"/><strong>{stageName(data.stage as Stage)}</strong></div><div className="field-grid"><label className="field"><span className="field-label">目标阶段</span><select className="form-control" aria-label="目标阶段" value={data.stage} onChange={e=>{const stage=e.target.value as Stage;setData(d=>({...d,stage,status:stage===job?.stage?stage==='result'?job.resultType:job.status:stage==='application'?'待投递':stage==='result'?'':'待安排',roundNotes:job?.rounds.find(r=>r.stage===stage&&r.round===d.round)?.notes||'',roundResult:job?.rounds.find(r=>r.stage===stage&&r.round===d.round)?.result||''}));}}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className={`field ${errors.status?'has-error':''}`}><span className="field-label">{data.stage==='result'?'求职结果':'阶段状态'}</span><select className="form-control" aria-label={data.stage==='result'?'求职结果':'阶段状态'} value={data.status} onChange={e=>update('status',e.target.value)}>{(data.stage==='result'?[['','请选择具体结果'],['offer','收到 Offer'],['rejected','未通过'],['withdrawn','主动退出']]:data.stage==='application'?[['待投递','待投递'],['已投递','已投递']]:[['待安排','待安排'],['待完成','待完成'],['待反馈','待反馈']]).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select><span className="field-error">{errors.status}</span></label>{field('轮次','round')}</div>
 {waiting&&<div className="feedback-completion-note"><Icon name="check" size={21}/><div><strong>{job?.action?'保存后，当前行动将完成并转入待反馈':'保存后开始等待反馈'}</strong><p>{job?.action||'当前没有待完成的行动。'}{job?.action&&<><br/>原行动与时间将保留在进展时间线中。</>}</p></div></div>}{actionFields}{['assessment','interview'].includes(data.stage)&&<section className="form-section"><h3>本轮记录</h3><div className="field-grid">{field('本轮结果','roundResult')}{field('本轮备注','roundNotes')}</div></section>}</>}
 </div><footer className="modal-footer"><span className="form-footnote">{mode==='record'?'* 为必填项':'历史会被保留'}</span><div><button className="button secondary" type="button" onClick={onClose}>取消</button><button className="button primary" type="submit">{busy?'正在保存…':mode==='record'?job?'保存修改':'创建记录':waiting&&job?.action?'完成并保存为待反馈':'保存进展'}</button></div></footer></fieldset></form></section></Dialog>;
}
